# Site settings
title: Smart Bikes
email: ilya@smart-bikes.ru
description: "Простой, удобный и качественный сервис проката современных велосипедов с использованием самых передовых технологий."
baseurl: ""
url: "http://smart-bikes.ru"

# Build settings
markdown: kramdown
permalink: pretty
