# Site settings
title: Smart Bikes
email: ilya.blan4@gmail.com
description: "Простой, удобный и качественный сервис проката современных велосипедов с использованием самых передовых технологий."
baseurl: ""
url: "https://blan4.github.io/SmartBikesLanding/"
form_url: "https://docs.google.com/forms/d/1rwuB_paVkJCBi5300xpx2KFHAO-EcYEHhFElbua0f78/viewform"

# Build settings
markdown: kramdown
permalink: pretty
