# Site settings
title: Smart Bikes
email: ilya@smart-bikes.ru
description: "Smart bikes"
baseurl: ""
url: "http://smart-bikes.ru"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
